### ISSUE TITLE
Add Jest support

### ISSUE THREAD

**Issue by hegelstad** [onury/jasmine-console-reporter#11]
Hi! 

I am using this reporter with Jest. Jest already has a summary to aggregates the jasmine (bundled) test runners results. 

It would therefore be nice to be able to have activity logging and test suites/specs defined without the summary :)

Also: 

- Execution time (ms) next to specs in Test suites & specs.
- Possibility to rename "test suites" and "specs" to "test" and "test cases" (jest syntax).

**Comment by onury** [comment]
Hi. For **Jest**, is it only the final summary part that should be disabled?
Or also "Pending Specs" and "Failed Specs" lists should be disabled?

I'm adding this option but it should also work for other users too.

**Comment by hegelstad** [comment]
For Jest it would be clean with:

Verbose logs from these levels: 0, 2 & 3.

I learned that jest will part with jasmine2 during the next months, but this should be a quick fix. 

Works well for debugging, but if tests are run in parallelle, stdin may be overwritten by jest unfornately for now.

> On 20 Aug 2018, at 22:54, Onur Yıldırım <notifications@github.com> wrote:
> 
> Hi. For Jest, is it only the final summary part that should be disabled?
> Or also "Pending Specs" and "Failed Specs" lists should be disabled?
> 
> I'm adding this option but it should also work for other users too.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 


REALIZE YOUR DIGITAL ROADMAP

Enterprise Intelligence Graph for 
Compliance, Governance, and Transformation

ardoq.com 
<https://ardoq.com/?utm_source=email_sig&utm_medium=email>

 
<https://content.ardoq.com/ardoq_mornings_copenhagen-11th-of-september-2018>

**Comment by onury** [comment]
Ok. I'll add these:
- spec timing 
- ability to disable summary

**Comment by onury** [comment]
Added.

**Comment by hegelstad** [comment]
Thanks!
