### ISSUE TITLE
Summary has disappeared in v3.1.0

### ISSUE THREAD

**Issue by cjuega** [onury/jasmine-console-reporter#12]
It seems summary is no longer displayed in v3.1.0. It used to be displayed in v3.0.2.

Is there any option to enable it back?

Here is my jasmine-console-reporter setup:
```js
{
    colors: 1,
    cleanStack: 1,
    verbosity: 4,
    listStyle: 'indent',
    activity: false,
    emoji: true,
    beep: true
}
```

**Comment by cjuega** [comment]
You are right, It was a wrong set up on my side. This issue can be safely closed.

Sorry!

**Comment by onury** [comment]
No problem.
