### ISSUE TITLE
Import instead of require

### ISSUE THREAD

**Issue by IgorJoin** [onury/jasmine-console-reporter#13]
First of all, that's a nice tool you have here! I'm using it in a protractor-typescript project and when setting it up in my conf.ts file, it seems it can't import jasmine-console-reporter. It'll only work with require. How can we use it according to typescript import?

**Comment by onury** [comment]
Thanks. Below should work:
```ts
import JasmineConsoleReporter from 'jasmine-console-reporter';
```
