### ISSUE TITLE
Expectation message gets lost on "reStack"

### ISSUE THREAD

**Issue by chris-equis** [onury/jasmine-console-reporter#3]
If the [expectation has a stack](https://github.com/onury/jasmine-console-reporter/blob/master/index.js#L223), utils.reStack gets called and there's no expectation message.

The returned error message says
"Error: Failed expectation" + stack, instead of "Error: Expected 5 to be 0"

**Comment by onury** [comment]
This was [fixed](https://github.com/onury/jasmine-console-reporter/commit/b1a11b29f13686e4e6448998b65201868dbb9365#diff-50e3aa130a4f97a42ee2cf111c7b1d9d) with v1.2.7
