### ISSUE TITLE
Feature: Show only focus tests

### ISSUE THREAD

**Issue by agirorn** [onury/jasmine-console-reporter#4]
When focusing on part of a test suite with (fdescribe or fit) it would be nice to only see the names of the tests under focus and not the names of all the tests as pending.

**Comment by onury** [comment]
Thanks. I'll look into it when I find time.

**Comment by onury** [comment]
Currently there is no possible way to do this. Jasmine does not mark focused suites or specs, it marks the rest as disabled; just like specs under a `xdescribe`.

All I can suggest for a cleaner summary is; you can set `verbosity` level to a lower value.

**Comment by onury** [comment]
Pls check v3.0.0 and re-open if needed.
