### ISSUE TITLE
Version 1.2.8 crashes due to updated Chalk dependency

### ISSUE THREAD

**Issue by pe8ter** [onury/jasmine-console-reporter#5]
Version 1.2.8 of `jasmine-console-reporter` upgraded its `chalk` dependency from 1.1.3 to 2.1.0. This introduced a crashing bug because `chalk` no longer has a `styles` property, but `jasmine-console-reporter` still tries to read it. See [this line](https://github.com/onury/jasmine-console-reporter/blob/f177eed7fb2cd14d1d3fcaefdc289ee5b83c9dd8/index.js#L107).

According to the [release notes for `chalk` version 2](https://github.com/chalk/chalk/releases/tag/v2.0.0), consumers should use the the styles from the `ansi-styles` package instead.

**Comment by onury** [comment]
Thanks for reporting. For now please set `colors` option to `1` (default).
I'll fix this and add extensive tests; then release v2.0.0 since `chalk` has a breaking change (Node.js version).
